### PR TITLE
Fix: make overlay accessible

### LINKED ISSUE #229: [BUG]: Update overlay modal to be accessible
**Describe the bug**
The overlay modal should use the native html `<dialog>` element so that the focus is managed correctly and the page behind becomes inert when opened.

Buttons within the overlay need accessible names and the "no search results found" should have role="alert" so that screen reader users are informed when the search fails to find results.

### PR DESCRIPTION
**Pull request by EmmaDawsonDev**
## Description
This PR updates the overlay component to use the native html `<dialog>` element. It also adds accessible names to the buttons within the overlay and announces to screen reader users when there are no search results.

## Issue
Closes #229 

## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

File: src/components/Overlay.tsx [hunk 1]
```diff
@@ -12,22 +12,29 @@ const Overlay = ({
...
+      dialogRef.current?.close()
+    }
+  })
   return (
-    <div
-      className={`fixed inset-0  flex items-center justify-center p-10 ${
-        isOpen ? 'block' : 'hidden'
-      } z-50 bg-gray-950/[.80] `}
+    <dialog
+      ref={dialogRef}
```
Comment (jamesqquick) [inline src/components/Overlay.tsx:26]: Can you add a `fixed` class to this to make sure it stays in position if the user scrolls?

**Review by jamesqquick — CHANGES_REQUESTED** [review]

**Review by jamesqquick — APPROVED** [review]
