### PR TITLE
fix(loading): match loading states with deal details

### LINKED ISSUE #248: [BUG]: Loading State on Deal Doesn't Match New Layout
**Describe the bug**
After updating the deal details page, the loading state doesn't match. The loading state should be updated accordingly.

**To Reproduce**
1. Go to the details page for a deal
2. See loading state, then UI change as data is loaded in

**Expected behavior**
Loading state should match the design of the details page.

### PR DESCRIPTION
**Pull request by jamesqquick**
Update loading states for deal details to match the `DealDetails.tsx` component

## Description
- added `LoadingText` component with properties for width and style
- added loading components for Tags

## Issue
Closes #248 

## Screenshot

https://github.com/user-attachments/assets/271b9ad6-c391-4ff0-b8cf-f1b8ba437f07

## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [x] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

File: src/components/deals/loading/LoadingPreview.tsx [hunk 1]
```diff
@@ -1,11 +1,65 @@
...
+} from './LoadingText'
 export default function LoadingPreview() {
   return (
-    <div className="flex flex-col items-start gap-10 text-white xl:flex-row xl:items-center">
-      <div className="align-center relative aspect-video w-full max-w-[600px] self-center">
-        <LoadingDealImage />
-      </div>
+    <div>
+      <Section
+        width={SECTION_WIDTH.SM}
```
Comment (joshmedeski) [inline src/components/deals/loading/LoadingPreview.tsx:12]: If possible, can you explain why you're mixing TailwindCSS with props that take enums? I find the multiple imports and inconsistent pattern here a bit confusion.

File: src/components/deals/loading/LoadingPreview.tsx [hunk 2]
```diff
@@ -1,11 +1,65 @@
+import Section, { SECTION_STYLE, SECTION_WIDTH } from '@/components/Section'
 import LoadingDealImage from './LoadingDealImage'
-
+import LoadingTagsList from './LoadingTagsList'
+import LoadingText, {
+  LOADING_TEXT_STYLE,
+  LOADING_TEXT_WIDHTS,
+} from './LoadingText'
```
Comment (joshmedeski) [inline src/components/deals/loading/LoadingPreview.tsx:7]: I find a line break between sections helpful (like imports and exports).

It feels cramped

**Review by joshmedeski — APPROVED** [review]
This looks great ✨

I have some questions about design decisions and a tip on breaking up chunks of code with line breaks.

But the code is great and ready to merge 💪

File: src/components/deals/loading/LoadingPreview.tsx (hunk 2 above)
Comment (jamesqquick) [reply src/components/deals/loading/LoadingPreview.tsx:7]: Yep, that's fair. I typically do. Don't know why not here. Added in latest commit!

File: src/components/deals/loading/LoadingPreview.tsx (hunk 1 above)
Comment (jamesqquick) [reply src/components/deals/loading/LoadingPreview.tsx:13]: In my mind they serve different purposes. The intent is to have a consistent set of options for width for the developer to choose from instead of writing those tailwind classes directly. These obviously get translated to translated to Tailwind classes in the component itself. This way, if those every need to change, we can change them in one place. Passing the `className` prop allows the developer to do any further customization that's needed, although that shouldn't be very often (hopefully).
