### PR TITLE
fix: overlay opens and closes appropritately

### LINKED ISSUE #250: [BUG]: Search Popup Fails to Open
**Describe the bug**
Search popup fails to open after being opened/closed once.

**To Reproduce**
1. Open search
2. Close search
3. Try to open search again
4. Search doesn't open

**Expected behavior**
Search should open whenever selected

**Screenshots**
CleanShot 2024-08-28 at 08.51.32.mp4

### PR DESCRIPTION
**Pull request by jamesqquick**
Search overlay failed to open a second time (after closing once)

## Description
- overlays handles `esc` key press and calls `onClose` function
- remove `esc` key handler in `GlobalSearch`
- move body overflow styles to `Overlay` so there is not scroll any time it is used

## Issue
Closes #250 

## Screenshot

https://github.com/user-attachments/assets/7e10a5d2-3d12-4e7f-a454-6f4bf8767a77

## PR Requirements

- [x] I have carefully read through and understand the [Deals-for-Devs Contributing Guide](https://github.com/Learn-Build-Teach/deals-for-devs/blob/dev/.github/contributing.md)
- [x] The title of this PR follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) format
- [x] The `Description` gives a good representation of the changes made
- [ ] If this PR addresses an open Issue, it is linked in the `Issue` section

### CODE REVIEW

File: src/components/search/GlobalSearch.tsx [hunk 1]
```diff
@@ -17,25 +17,17 @@ export default function GlobalSearch() {
...
-  }, [searchOpen])
-
   const openSearch = () => {
     setSearchOpen(true)
-    document.body.style.overflow = 'hidden'
     inputRef?.current?.focus()
   }
 
-  const reset = () => {
+  const closeSearch = () => {
```
Comment (joshmedeski) [inline src/components/search/GlobalSearch.tsx:25]: I think `reset` was a better name, or `onClose`.

This is an event on close, so technically saying `closeSearch` is inaccurate as this code isn't closing the search.

File: src/components/Overlay.tsx [hunk 2]
```diff
@@ -17,13 +17,17 @@ const Overlay = ({
...
   const dialogRef = useRef<HTMLDialogElement>(null)
-  useHotkeys('esc', onClose)
+  useHotkeys('esc', () => {
+    onClose()
+  })
 
   useEffect(() => {
     if (isOpen) {
       dialogRef.current?.showModal()
+      document.body.style.overflow = 'hidden'
```
Comment (joshmedeski) [inline src/components/Overlay.tsx:27]: Please test shorter window sizes, my main concern is the user won't be able to access search results if they're out of view.

**Review by joshmedeski — CHANGES_REQUESTED** [review]
A few minor concerns.

File: src/components/Overlay.tsx (hunk 2 above)
Comment (jamesqquick) [reply src/components/Overlay.tsx:27]: Great call. Looks like it still works because the overlay content itself is scrollable even when the content behind it is not, so we're still good.

https://github.com/user-attachments/assets/6073d33e-6718-41e5-99d4-efb664f290ce

File: src/components/search/GlobalSearch.tsx (hunk 1 above)
Comment (jamesqquick) [reply src/components/search/GlobalSearch.tsx]: Makes sense. Renamed to `onClose` in latest commit!

**Review by joshmedeski — APPROVED** [review]
Thanks for looking those items over. Looks good to me 👍
